[package]
name = "image_watermark_test"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
clap = { version = "4.0", features = ["derive"] }
resvg = "0.45.1"
usvg = "0.45.1"
tiny-skia = "0.11"
