[package]
name = "auto_layout_render_test"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
rusttype = "0.9"
imageproc = "0.23"
cassowary = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
rgb = "0.8"
